
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class NautobotCloudAccount(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotCloudService(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotCluster(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotDevice(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotDeviceGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotEnumCloudProvider(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotEnumOperationalStatus(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotIPAddress(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotLocation(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotPrefix(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotSoftwareVersion(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotTag(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotTenant(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotVirtualMachine(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NautobotVLAN(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
